import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.goto('http://localhost:5173/signin');
  await page.getByPlaceholder('Enter username').click();
  await page.getByPlaceholder('Enter username').fill('admin');
  await page.getByPlaceholder('Enter username').press('Tab');
  await page.getByPlaceholder('Enter password').fill('admin');
  await page.getByPlaceholder('Enter password').press('Enter');
  await page.getByText('New Patient\'s Name').nth(3).click();
  await page.getByRole('link', { name: 'Past Medical History' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.locator('input[name="tuberculosis"]').first().check();
  await page.locator('input[name="diabetes"]').first().check();
  await page.locator('input[name="hypertension"]').first().check();
  await page.locator('input[name="hyperlipidemia"]').first().check();
  await page.locator('input[name="chronic-joint-pains"]').nth(1).check();
  await page.locator('div:nth-child(9) > div > div:nth-child(3)').click();
  await page.locator('input[name="chronic-muscle-aches"]').nth(1).check();
  await page.locator('input[name="std"]').nth(1).check();
  await page.getByRole('button', { name: 'Save Edits' }).click();
  await page.getByRole('link', { name: 'Social History' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.locator('input[name="smoking-hist"]').nth(1).check();
  await page.locator('input[name="curr-smoking-hist"]').nth(1).check();
  await page.locator('input[name="alc-hist"]').nth(1).check();
  await page.getByRole('button', { name: 'Save Edits' }).click();
  await page.getByRole('link', { name: 'Vital Statistics' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByPlaceholder('Degree Celsius').click();
  await page.getByPlaceholder('Degree Celsius').fill('36.1');
  await page.getByPlaceholder('%').click();
  await page.getByPlaceholder('%').fill('95');
  await page.getByPlaceholder('mmHg').first().click();
  await page.getByPlaceholder('mmHg').first().fill('115');
  await page.getByPlaceholder('mmHg').nth(1).click();
  await page.getByPlaceholder('mmHg').nth(1).fill('115');
  await page.getByPlaceholder('mmHg').nth(2).click();
  await page.getByPlaceholder('mmHg').nth(2).fill('53');
  await page.getByPlaceholder('mmHg').nth(3).click();
  await page.getByPlaceholder('mmHg').nth(3).fill('93');
  await page.getByPlaceholder('BPM').first().click();
  await page.getByPlaceholder('BPM').first().fill('99');
  await page.getByPlaceholder('BPM').nth(1).click();
  await page.getByPlaceholder('BPM').nth(1).fill('87');
  await page.getByPlaceholder('mmol/L').click();
  await page.getByPlaceholder('mmol/L').fill('6.9');
  await page.getByPlaceholder('mg/dL').click();
  await page.getByPlaceholder('mg/dL').fill('124.2');
  await page.getByRole('button', { name: 'Save Edits' }).click();
});